// Code generated by entc, DO NOT EDIT.

package problemstatus

const (
	// Label holds the string label denoting the problemstatus type in the database.
	Label = "problem_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProblemstatus holds the string denoting the problemstatus field in the database.
	FieldProblemstatus = "problemstatus"

	// EdgeProblemstatus2problem holds the string denoting the problemstatus2problem edge name in mutations.
	EdgeProblemstatus2problem = "problemstatus2problem"

	// Table holds the table name of the problemstatus in the database.
	Table = "problem_status"
	// Problemstatus2problemTable is the table the holds the problemstatus2problem relation/edge.
	Problemstatus2problemTable = "problems"
	// Problemstatus2problemInverseTable is the table name for the Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problem" package.
	Problemstatus2problemInverseTable = "problems"
	// Problemstatus2problemColumn is the table column denoting the problemstatus2problem relation/edge.
	Problemstatus2problemColumn = "problemstatus"
)

// Columns holds all SQL columns for problemstatus fields.
var Columns = []string{
	FieldID,
	FieldProblemstatus,
}

var (
	// ProblemstatusValidator is a validator for the "problemstatus" field. It is called by the builders before save.
	ProblemstatusValidator func(string) error
)
