// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Problem is the predicate function for problem builders.
type Problem func(*sql.Selector)

// ProblemStatus is the predicate function for problemstatus builders.
type ProblemStatus func(*sql.Selector)

// ProblemTitle is the predicate function for problemtitle builders.
type ProblemTitle func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
