// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/thanawat/app/ent/predicate"
	"github.com/thanawat/app/ent/problemstatus"
)

// ProblemStatusDelete is the builder for deleting a ProblemStatus entity.
type ProblemStatusDelete struct {
	config
	hooks      []Hook
	mutation   *ProblemStatusMutation
	predicates []predicate.ProblemStatus
}

// Where adds a new predicate to the delete builder.
func (psd *ProblemStatusDelete) Where(ps ...predicate.ProblemStatus) *ProblemStatusDelete {
	psd.predicates = append(psd.predicates, ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *ProblemStatusDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(psd.hooks) == 0 {
		affected, err = psd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProblemStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			psd.mutation = mutation
			affected, err = psd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(psd.hooks) - 1; i >= 0; i-- {
			mut = psd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, psd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *ProblemStatusDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *ProblemStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: problemstatus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: problemstatus.FieldID,
			},
		},
	}
	if ps := psd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
}

// ProblemStatusDeleteOne is the builder for deleting a single ProblemStatus entity.
type ProblemStatusDeleteOne struct {
	psd *ProblemStatusDelete
}

// Exec executes the deletion query.
func (psdo *ProblemStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{problemstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *ProblemStatusDeleteOne) ExecX(ctx context.Context) {
	psdo.psd.ExecX(ctx)
}
