// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/thanawat/app/ent/predicate"
	"github.com/thanawat/app/ent/problem"
	"github.com/thanawat/app/ent/problemstatus"
	"github.com/thanawat/app/ent/problemtitle"
	"github.com/thanawat/app/ent/room"
	"github.com/thanawat/app/ent/user"
)

// ProblemUpdate is the builder for updating Problem entities.
type ProblemUpdate struct {
	config
	hooks      []Hook
	mutation   *ProblemMutation
	predicates []predicate.Problem
}

// Where adds a new predicate for the builder.
func (pu *ProblemUpdate) Where(ps ...predicate.Problem) *ProblemUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetProbleminfo sets the probleminfo field.
func (pu *ProblemUpdate) SetProbleminfo(s string) *ProblemUpdate {
	pu.mutation.SetProbleminfo(s)
	return pu
}

// SetAdddate sets the adddate field.
func (pu *ProblemUpdate) SetAdddate(t time.Time) *ProblemUpdate {
	pu.mutation.SetAdddate(t)
	return pu
}

// SetUserID sets the user edge to User by id.
func (pu *ProblemUpdate) SetUserID(id int) *ProblemUpdate {
	pu.mutation.SetUserID(id)
	return pu
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (pu *ProblemUpdate) SetNillableUserID(id *int) *ProblemUpdate {
	if id != nil {
		pu = pu.SetUserID(*id)
	}
	return pu
}

// SetUser sets the user edge to User.
func (pu *ProblemUpdate) SetUser(u *User) *ProblemUpdate {
	return pu.SetUserID(u.ID)
}

// SetRoomID sets the room edge to Room by id.
func (pu *ProblemUpdate) SetRoomID(id int) *ProblemUpdate {
	pu.mutation.SetRoomID(id)
	return pu
}

// SetNillableRoomID sets the room edge to Room by id if the given value is not nil.
func (pu *ProblemUpdate) SetNillableRoomID(id *int) *ProblemUpdate {
	if id != nil {
		pu = pu.SetRoomID(*id)
	}
	return pu
}

// SetRoom sets the room edge to Room.
func (pu *ProblemUpdate) SetRoom(r *Room) *ProblemUpdate {
	return pu.SetRoomID(r.ID)
}

// SetProblemtitleID sets the problemtitle edge to ProblemTitle by id.
func (pu *ProblemUpdate) SetProblemtitleID(id int) *ProblemUpdate {
	pu.mutation.SetProblemtitleID(id)
	return pu
}

// SetNillableProblemtitleID sets the problemtitle edge to ProblemTitle by id if the given value is not nil.
func (pu *ProblemUpdate) SetNillableProblemtitleID(id *int) *ProblemUpdate {
	if id != nil {
		pu = pu.SetProblemtitleID(*id)
	}
	return pu
}

// SetProblemtitle sets the problemtitle edge to ProblemTitle.
func (pu *ProblemUpdate) SetProblemtitle(p *ProblemTitle) *ProblemUpdate {
	return pu.SetProblemtitleID(p.ID)
}

// SetProblemstatusID sets the problemstatus edge to ProblemStatus by id.
func (pu *ProblemUpdate) SetProblemstatusID(id int) *ProblemUpdate {
	pu.mutation.SetProblemstatusID(id)
	return pu
}

// SetNillableProblemstatusID sets the problemstatus edge to ProblemStatus by id if the given value is not nil.
func (pu *ProblemUpdate) SetNillableProblemstatusID(id *int) *ProblemUpdate {
	if id != nil {
		pu = pu.SetProblemstatusID(*id)
	}
	return pu
}

// SetProblemstatus sets the problemstatus edge to ProblemStatus.
func (pu *ProblemUpdate) SetProblemstatus(p *ProblemStatus) *ProblemUpdate {
	return pu.SetProblemstatusID(p.ID)
}

// Mutation returns the ProblemMutation object of the builder.
func (pu *ProblemUpdate) Mutation() *ProblemMutation {
	return pu.mutation
}

// ClearUser clears the user edge to User.
func (pu *ProblemUpdate) ClearUser() *ProblemUpdate {
	pu.mutation.ClearUser()
	return pu
}

// ClearRoom clears the room edge to Room.
func (pu *ProblemUpdate) ClearRoom() *ProblemUpdate {
	pu.mutation.ClearRoom()
	return pu
}

// ClearProblemtitle clears the problemtitle edge to ProblemTitle.
func (pu *ProblemUpdate) ClearProblemtitle() *ProblemUpdate {
	pu.mutation.ClearProblemtitle()
	return pu
}

// ClearProblemstatus clears the problemstatus edge to ProblemStatus.
func (pu *ProblemUpdate) ClearProblemstatus() *ProblemUpdate {
	pu.mutation.ClearProblemstatus()
	return pu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *ProblemUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := pu.mutation.Probleminfo(); ok {
		if err := problem.ProbleminfoValidator(v); err != nil {
			return 0, &ValidationError{Name: "probleminfo", err: fmt.Errorf("ent: validator failed for field \"probleminfo\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProblemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProblemUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProblemUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProblemUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *ProblemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   problem.Table,
			Columns: problem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: problem.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Probleminfo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: problem.FieldProbleminfo,
		})
	}
	if value, ok := pu.mutation.Adddate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: problem.FieldAdddate,
		})
	}
	if pu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.UserTable,
			Columns: []string{problem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.UserTable,
			Columns: []string{problem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.RoomTable,
			Columns: []string{problem.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.RoomTable,
			Columns: []string{problem.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.ProblemtitleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.ProblemtitleTable,
			Columns: []string{problem.ProblemtitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problemtitle.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ProblemtitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.ProblemtitleTable,
			Columns: []string{problem.ProblemtitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problemtitle.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.ProblemstatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.ProblemstatusTable,
			Columns: []string{problem.ProblemstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problemstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ProblemstatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.ProblemstatusTable,
			Columns: []string{problem.ProblemstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problemstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problem.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ProblemUpdateOne is the builder for updating a single Problem entity.
type ProblemUpdateOne struct {
	config
	hooks    []Hook
	mutation *ProblemMutation
}

// SetProbleminfo sets the probleminfo field.
func (puo *ProblemUpdateOne) SetProbleminfo(s string) *ProblemUpdateOne {
	puo.mutation.SetProbleminfo(s)
	return puo
}

// SetAdddate sets the adddate field.
func (puo *ProblemUpdateOne) SetAdddate(t time.Time) *ProblemUpdateOne {
	puo.mutation.SetAdddate(t)
	return puo
}

// SetUserID sets the user edge to User by id.
func (puo *ProblemUpdateOne) SetUserID(id int) *ProblemUpdateOne {
	puo.mutation.SetUserID(id)
	return puo
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (puo *ProblemUpdateOne) SetNillableUserID(id *int) *ProblemUpdateOne {
	if id != nil {
		puo = puo.SetUserID(*id)
	}
	return puo
}

// SetUser sets the user edge to User.
func (puo *ProblemUpdateOne) SetUser(u *User) *ProblemUpdateOne {
	return puo.SetUserID(u.ID)
}

// SetRoomID sets the room edge to Room by id.
func (puo *ProblemUpdateOne) SetRoomID(id int) *ProblemUpdateOne {
	puo.mutation.SetRoomID(id)
	return puo
}

// SetNillableRoomID sets the room edge to Room by id if the given value is not nil.
func (puo *ProblemUpdateOne) SetNillableRoomID(id *int) *ProblemUpdateOne {
	if id != nil {
		puo = puo.SetRoomID(*id)
	}
	return puo
}

// SetRoom sets the room edge to Room.
func (puo *ProblemUpdateOne) SetRoom(r *Room) *ProblemUpdateOne {
	return puo.SetRoomID(r.ID)
}

// SetProblemtitleID sets the problemtitle edge to ProblemTitle by id.
func (puo *ProblemUpdateOne) SetProblemtitleID(id int) *ProblemUpdateOne {
	puo.mutation.SetProblemtitleID(id)
	return puo
}

// SetNillableProblemtitleID sets the problemtitle edge to ProblemTitle by id if the given value is not nil.
func (puo *ProblemUpdateOne) SetNillableProblemtitleID(id *int) *ProblemUpdateOne {
	if id != nil {
		puo = puo.SetProblemtitleID(*id)
	}
	return puo
}

// SetProblemtitle sets the problemtitle edge to ProblemTitle.
func (puo *ProblemUpdateOne) SetProblemtitle(p *ProblemTitle) *ProblemUpdateOne {
	return puo.SetProblemtitleID(p.ID)
}

// SetProblemstatusID sets the problemstatus edge to ProblemStatus by id.
func (puo *ProblemUpdateOne) SetProblemstatusID(id int) *ProblemUpdateOne {
	puo.mutation.SetProblemstatusID(id)
	return puo
}

// SetNillableProblemstatusID sets the problemstatus edge to ProblemStatus by id if the given value is not nil.
func (puo *ProblemUpdateOne) SetNillableProblemstatusID(id *int) *ProblemUpdateOne {
	if id != nil {
		puo = puo.SetProblemstatusID(*id)
	}
	return puo
}

// SetProblemstatus sets the problemstatus edge to ProblemStatus.
func (puo *ProblemUpdateOne) SetProblemstatus(p *ProblemStatus) *ProblemUpdateOne {
	return puo.SetProblemstatusID(p.ID)
}

// Mutation returns the ProblemMutation object of the builder.
func (puo *ProblemUpdateOne) Mutation() *ProblemMutation {
	return puo.mutation
}

// ClearUser clears the user edge to User.
func (puo *ProblemUpdateOne) ClearUser() *ProblemUpdateOne {
	puo.mutation.ClearUser()
	return puo
}

// ClearRoom clears the room edge to Room.
func (puo *ProblemUpdateOne) ClearRoom() *ProblemUpdateOne {
	puo.mutation.ClearRoom()
	return puo
}

// ClearProblemtitle clears the problemtitle edge to ProblemTitle.
func (puo *ProblemUpdateOne) ClearProblemtitle() *ProblemUpdateOne {
	puo.mutation.ClearProblemtitle()
	return puo
}

// ClearProblemstatus clears the problemstatus edge to ProblemStatus.
func (puo *ProblemUpdateOne) ClearProblemstatus() *ProblemUpdateOne {
	puo.mutation.ClearProblemstatus()
	return puo
}

// Save executes the query and returns the updated entity.
func (puo *ProblemUpdateOne) Save(ctx context.Context) (*Problem, error) {
	if v, ok := puo.mutation.Probleminfo(); ok {
		if err := problem.ProbleminfoValidator(v); err != nil {
			return nil, &ValidationError{Name: "probleminfo", err: fmt.Errorf("ent: validator failed for field \"probleminfo\": %w", err)}
		}
	}

	var (
		err  error
		node *Problem
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProblemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProblemUpdateOne) SaveX(ctx context.Context) *Problem {
	pr, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return pr
}

// Exec executes the query on the entity.
func (puo *ProblemUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProblemUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *ProblemUpdateOne) sqlSave(ctx context.Context) (pr *Problem, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   problem.Table,
			Columns: problem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: problem.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Problem.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.Probleminfo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: problem.FieldProbleminfo,
		})
	}
	if value, ok := puo.mutation.Adddate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: problem.FieldAdddate,
		})
	}
	if puo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.UserTable,
			Columns: []string{problem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.UserTable,
			Columns: []string{problem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.RoomTable,
			Columns: []string{problem.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.RoomTable,
			Columns: []string{problem.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.ProblemtitleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.ProblemtitleTable,
			Columns: []string{problem.ProblemtitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problemtitle.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ProblemtitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.ProblemtitleTable,
			Columns: []string{problem.ProblemtitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problemtitle.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.ProblemstatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.ProblemstatusTable,
			Columns: []string{problem.ProblemstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problemstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ProblemstatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.ProblemstatusTable,
			Columns: []string{problem.ProblemstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problemstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	pr = &Problem{config: puo.config}
	_spec.Assign = pr.assignValues
	_spec.ScanValues = pr.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problem.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return pr, nil
}
