// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/thanawat/app/ent/predicate"
	"github.com/thanawat/app/ent/problem"
	"github.com/thanawat/app/ent/problemtitle"
)

// ProblemTitleUpdate is the builder for updating ProblemTitle entities.
type ProblemTitleUpdate struct {
	config
	hooks      []Hook
	mutation   *ProblemTitleMutation
	predicates []predicate.ProblemTitle
}

// Where adds a new predicate for the builder.
func (ptu *ProblemTitleUpdate) Where(ps ...predicate.ProblemTitle) *ProblemTitleUpdate {
	ptu.predicates = append(ptu.predicates, ps...)
	return ptu
}

// SetProblemtitle sets the problemtitle field.
func (ptu *ProblemTitleUpdate) SetProblemtitle(s string) *ProblemTitleUpdate {
	ptu.mutation.SetProblemtitle(s)
	return ptu
}

// AddProblemtitle2problemIDs adds the problemtitle2problem edge to Problem by ids.
func (ptu *ProblemTitleUpdate) AddProblemtitle2problemIDs(ids ...int) *ProblemTitleUpdate {
	ptu.mutation.AddProblemtitle2problemIDs(ids...)
	return ptu
}

// AddProblemtitle2problem adds the problemtitle2problem edges to Problem.
func (ptu *ProblemTitleUpdate) AddProblemtitle2problem(p ...*Problem) *ProblemTitleUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptu.AddProblemtitle2problemIDs(ids...)
}

// Mutation returns the ProblemTitleMutation object of the builder.
func (ptu *ProblemTitleUpdate) Mutation() *ProblemTitleMutation {
	return ptu.mutation
}

// RemoveProblemtitle2problemIDs removes the problemtitle2problem edge to Problem by ids.
func (ptu *ProblemTitleUpdate) RemoveProblemtitle2problemIDs(ids ...int) *ProblemTitleUpdate {
	ptu.mutation.RemoveProblemtitle2problemIDs(ids...)
	return ptu
}

// RemoveProblemtitle2problem removes problemtitle2problem edges to Problem.
func (ptu *ProblemTitleUpdate) RemoveProblemtitle2problem(p ...*Problem) *ProblemTitleUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptu.RemoveProblemtitle2problemIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ptu *ProblemTitleUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := ptu.mutation.Problemtitle(); ok {
		if err := problemtitle.ProblemtitleValidator(v); err != nil {
			return 0, &ValidationError{Name: "problemtitle", err: fmt.Errorf("ent: validator failed for field \"problemtitle\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(ptu.hooks) == 0 {
		affected, err = ptu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProblemTitleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ptu.mutation = mutation
			affected, err = ptu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ptu.hooks) - 1; i >= 0; i-- {
			mut = ptu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ptu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ptu *ProblemTitleUpdate) SaveX(ctx context.Context) int {
	affected, err := ptu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ptu *ProblemTitleUpdate) Exec(ctx context.Context) error {
	_, err := ptu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptu *ProblemTitleUpdate) ExecX(ctx context.Context) {
	if err := ptu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ptu *ProblemTitleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   problemtitle.Table,
			Columns: problemtitle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: problemtitle.FieldID,
			},
		},
	}
	if ps := ptu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ptu.mutation.Problemtitle(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: problemtitle.FieldProblemtitle,
		})
	}
	if nodes := ptu.mutation.RemovedProblemtitle2problemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtitle.Problemtitle2problemTable,
			Columns: []string{problemtitle.Problemtitle2problemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptu.mutation.Problemtitle2problemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtitle.Problemtitle2problemTable,
			Columns: []string{problemtitle.Problemtitle2problemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ptu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemtitle.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ProblemTitleUpdateOne is the builder for updating a single ProblemTitle entity.
type ProblemTitleUpdateOne struct {
	config
	hooks    []Hook
	mutation *ProblemTitleMutation
}

// SetProblemtitle sets the problemtitle field.
func (ptuo *ProblemTitleUpdateOne) SetProblemtitle(s string) *ProblemTitleUpdateOne {
	ptuo.mutation.SetProblemtitle(s)
	return ptuo
}

// AddProblemtitle2problemIDs adds the problemtitle2problem edge to Problem by ids.
func (ptuo *ProblemTitleUpdateOne) AddProblemtitle2problemIDs(ids ...int) *ProblemTitleUpdateOne {
	ptuo.mutation.AddProblemtitle2problemIDs(ids...)
	return ptuo
}

// AddProblemtitle2problem adds the problemtitle2problem edges to Problem.
func (ptuo *ProblemTitleUpdateOne) AddProblemtitle2problem(p ...*Problem) *ProblemTitleUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptuo.AddProblemtitle2problemIDs(ids...)
}

// Mutation returns the ProblemTitleMutation object of the builder.
func (ptuo *ProblemTitleUpdateOne) Mutation() *ProblemTitleMutation {
	return ptuo.mutation
}

// RemoveProblemtitle2problemIDs removes the problemtitle2problem edge to Problem by ids.
func (ptuo *ProblemTitleUpdateOne) RemoveProblemtitle2problemIDs(ids ...int) *ProblemTitleUpdateOne {
	ptuo.mutation.RemoveProblemtitle2problemIDs(ids...)
	return ptuo
}

// RemoveProblemtitle2problem removes problemtitle2problem edges to Problem.
func (ptuo *ProblemTitleUpdateOne) RemoveProblemtitle2problem(p ...*Problem) *ProblemTitleUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptuo.RemoveProblemtitle2problemIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (ptuo *ProblemTitleUpdateOne) Save(ctx context.Context) (*ProblemTitle, error) {
	if v, ok := ptuo.mutation.Problemtitle(); ok {
		if err := problemtitle.ProblemtitleValidator(v); err != nil {
			return nil, &ValidationError{Name: "problemtitle", err: fmt.Errorf("ent: validator failed for field \"problemtitle\": %w", err)}
		}
	}

	var (
		err  error
		node *ProblemTitle
	)
	if len(ptuo.hooks) == 0 {
		node, err = ptuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProblemTitleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ptuo.mutation = mutation
			node, err = ptuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ptuo.hooks) - 1; i >= 0; i-- {
			mut = ptuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ptuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ptuo *ProblemTitleUpdateOne) SaveX(ctx context.Context) *ProblemTitle {
	pt, err := ptuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return pt
}

// Exec executes the query on the entity.
func (ptuo *ProblemTitleUpdateOne) Exec(ctx context.Context) error {
	_, err := ptuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptuo *ProblemTitleUpdateOne) ExecX(ctx context.Context) {
	if err := ptuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ptuo *ProblemTitleUpdateOne) sqlSave(ctx context.Context) (pt *ProblemTitle, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   problemtitle.Table,
			Columns: problemtitle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: problemtitle.FieldID,
			},
		},
	}
	id, ok := ptuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing ProblemTitle.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ptuo.mutation.Problemtitle(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: problemtitle.FieldProblemtitle,
		})
	}
	if nodes := ptuo.mutation.RemovedProblemtitle2problemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtitle.Problemtitle2problemTable,
			Columns: []string{problemtitle.Problemtitle2problemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptuo.mutation.Problemtitle2problemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtitle.Problemtitle2problemTable,
			Columns: []string{problemtitle.Problemtitle2problemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	pt = &ProblemTitle{config: ptuo.config}
	_spec.Assign = pt.assignValues
	_spec.ScanValues = pt.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ptuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemtitle.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return pt, nil
}
