// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/thanawat/app/ent/problem"
	"github.com/thanawat/app/ent/problemtitle"
)

// ProblemTitleCreate is the builder for creating a ProblemTitle entity.
type ProblemTitleCreate struct {
	config
	mutation *ProblemTitleMutation
	hooks    []Hook
}

// SetProblemtitle sets the problemtitle field.
func (ptc *ProblemTitleCreate) SetProblemtitle(s string) *ProblemTitleCreate {
	ptc.mutation.SetProblemtitle(s)
	return ptc
}

// AddProblemtitle2problemIDs adds the problemtitle2problem edge to Problem by ids.
func (ptc *ProblemTitleCreate) AddProblemtitle2problemIDs(ids ...int) *ProblemTitleCreate {
	ptc.mutation.AddProblemtitle2problemIDs(ids...)
	return ptc
}

// AddProblemtitle2problem adds the problemtitle2problem edges to Problem.
func (ptc *ProblemTitleCreate) AddProblemtitle2problem(p ...*Problem) *ProblemTitleCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptc.AddProblemtitle2problemIDs(ids...)
}

// Mutation returns the ProblemTitleMutation object of the builder.
func (ptc *ProblemTitleCreate) Mutation() *ProblemTitleMutation {
	return ptc.mutation
}

// Save creates the ProblemTitle in the database.
func (ptc *ProblemTitleCreate) Save(ctx context.Context) (*ProblemTitle, error) {
	if _, ok := ptc.mutation.Problemtitle(); !ok {
		return nil, &ValidationError{Name: "problemtitle", err: errors.New("ent: missing required field \"problemtitle\"")}
	}
	if v, ok := ptc.mutation.Problemtitle(); ok {
		if err := problemtitle.ProblemtitleValidator(v); err != nil {
			return nil, &ValidationError{Name: "problemtitle", err: fmt.Errorf("ent: validator failed for field \"problemtitle\": %w", err)}
		}
	}
	var (
		err  error
		node *ProblemTitle
	)
	if len(ptc.hooks) == 0 {
		node, err = ptc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProblemTitleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ptc.mutation = mutation
			node, err = ptc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ptc.hooks) - 1; i >= 0; i-- {
			mut = ptc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ptc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ptc *ProblemTitleCreate) SaveX(ctx context.Context) *ProblemTitle {
	v, err := ptc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ptc *ProblemTitleCreate) sqlSave(ctx context.Context) (*ProblemTitle, error) {
	pt, _spec := ptc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ptc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pt.ID = int(id)
	return pt, nil
}

func (ptc *ProblemTitleCreate) createSpec() (*ProblemTitle, *sqlgraph.CreateSpec) {
	var (
		pt    = &ProblemTitle{config: ptc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: problemtitle.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: problemtitle.FieldID,
			},
		}
	)
	if value, ok := ptc.mutation.Problemtitle(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: problemtitle.FieldProblemtitle,
		})
		pt.Problemtitle = value
	}
	if nodes := ptc.mutation.Problemtitle2problemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtitle.Problemtitle2problemTable,
			Columns: []string{problemtitle.Problemtitle2problemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pt, _spec
}
