// Code generated by entc, DO NOT EDIT.

package problemtitle

const (
	// Label holds the string label denoting the problemtitle type in the database.
	Label = "problem_title"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProblemtitle holds the string denoting the problemtitle field in the database.
	FieldProblemtitle = "problemtitle"

	// EdgeProblemtitle2problem holds the string denoting the problemtitle2problem edge name in mutations.
	EdgeProblemtitle2problem = "problemtitle2problem"

	// Table holds the table name of the problemtitle in the database.
	Table = "problem_titles"
	// Problemtitle2problemTable is the table the holds the problemtitle2problem relation/edge.
	Problemtitle2problemTable = "problems"
	// Problemtitle2problemInverseTable is the table name for the Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problem" package.
	Problemtitle2problemInverseTable = "problems"
	// Problemtitle2problemColumn is the table column denoting the problemtitle2problem relation/edge.
	Problemtitle2problemColumn = "problemtitle"
)

// Columns holds all SQL columns for problemtitle fields.
var Columns = []string{
	FieldID,
	FieldProblemtitle,
}

var (
	// ProblemtitleValidator is a validator for the "problemtitle" field. It is called by the builders before save.
	ProblemtitleValidator func(string) error
)
