/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersProblem
 */
export interface ControllersProblem {
    /**
     * 
     * @type {string}
     * @memberof ControllersProblem
     */
    added?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersProblem
     */
    probleminfo?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersProblem
     */
    problemstatus?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersProblem
     */
    problemtitle?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersProblem
     */
    room?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersProblem
     */
    user?: number;
}

export function ControllersProblemFromJSON(json: any): ControllersProblem {
    return ControllersProblemFromJSONTyped(json, false);
}

export function ControllersProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersProblem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'added': !exists(json, 'added') ? undefined : json['added'],
        'probleminfo': !exists(json, 'probleminfo') ? undefined : json['probleminfo'],
        'problemstatus': !exists(json, 'problemstatus') ? undefined : json['problemstatus'],
        'problemtitle': !exists(json, 'problemtitle') ? undefined : json['problemtitle'],
        'room': !exists(json, 'room') ? undefined : json['room'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function ControllersProblemToJSON(value?: ControllersProblem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added': value.added,
        'probleminfo': value.probleminfo,
        'problemstatus': value.problemstatus,
        'problemtitle': value.problemtitle,
        'room': value.room,
        'user': value.user,
    };
}


