/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntProblemStatusEdges,
    EntProblemStatusEdgesFromJSON,
    EntProblemStatusEdgesFromJSONTyped,
    EntProblemStatusEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntProblemStatus
 */
export interface EntProblemStatus {
    /**
     * 
     * @type {EntProblemStatusEdges}
     * @memberof EntProblemStatus
     */
    edges?: EntProblemStatusEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntProblemStatus
     */
    id?: number;
    /**
     * Problemstatus holds the value of the "problemstatus" field.
     * @type {string}
     * @memberof EntProblemStatus
     */
    problemstatus?: string;
}

export function EntProblemStatusFromJSON(json: any): EntProblemStatus {
    return EntProblemStatusFromJSONTyped(json, false);
}

export function EntProblemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntProblemStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntProblemStatusEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'problemstatus': !exists(json, 'problemstatus') ? undefined : json['problemstatus'],
    };
}

export function EntProblemStatusToJSON(value?: EntProblemStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntProblemStatusEdgesToJSON(value.edges),
        'id': value.id,
        'problemstatus': value.problemstatus,
    };
}


