/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntProblemTitleEdges,
    EntProblemTitleEdgesFromJSON,
    EntProblemTitleEdgesFromJSONTyped,
    EntProblemTitleEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntProblemTitle
 */
export interface EntProblemTitle {
    /**
     * 
     * @type {EntProblemTitleEdges}
     * @memberof EntProblemTitle
     */
    edges?: EntProblemTitleEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntProblemTitle
     */
    id?: number;
    /**
     * Problemtitle holds the value of the "problemtitle" field.
     * @type {string}
     * @memberof EntProblemTitle
     */
    problemtitle?: string;
}

export function EntProblemTitleFromJSON(json: any): EntProblemTitle {
    return EntProblemTitleFromJSONTyped(json, false);
}

export function EntProblemTitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntProblemTitle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntProblemTitleEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'problemtitle': !exists(json, 'problemtitle') ? undefined : json['problemtitle'],
    };
}

export function EntProblemTitleToJSON(value?: EntProblemTitle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntProblemTitleEdgesToJSON(value.edges),
        'id': value.id,
        'problemtitle': value.problemtitle,
    };
}


