/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntProblem,
    EntProblemFromJSON,
    EntProblemFromJSONTyped,
    EntProblemToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomEdges
 */
export interface EntRoomEdges {
    /**
     * Room2problem holds the value of the room2problem edge.
     * @type {Array<EntProblem>}
     * @memberof EntRoomEdges
     */
    room2problem?: Array<EntProblem>;
    /**
     * 
     * @type {EntUser}
     * @memberof EntRoomEdges
     */
    user?: EntUser;
}

export function EntRoomEdgesFromJSON(json: any): EntRoomEdges {
    return EntRoomEdgesFromJSONTyped(json, false);
}

export function EntRoomEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'room2problem': !exists(json, 'room2problem') ? undefined : ((json['room2problem'] as Array<any>).map(EntProblemFromJSON)),
        'user': !exists(json, 'user') ? undefined : EntUserFromJSON(json['user']),
    };
}

export function EntRoomEdgesToJSON(value?: EntRoomEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'room2problem': value.room2problem === undefined ? undefined : ((value.room2problem as Array<any>).map(EntProblemToJSON)),
        'user': EntUserToJSON(value.user),
    };
}


