// Code generated by entc, DO NOT EDIT.

package room

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeRoom2problem holds the string denoting the room2problem edge name in mutations.
	EdgeRoom2problem = "room2problem"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "rooms"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// Room2problemTable is the table the holds the room2problem relation/edge.
	Room2problemTable = "problems"
	// Room2problemInverseTable is the table name for the Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problem" package.
	Room2problemInverseTable = "problems"
	// Room2problemColumn is the table column denoting the room2problem relation/edge.
	Room2problemColumn = "room_id"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Room type.
var ForeignKeys = []string{
	"user_id",
}
